# Generated by Django 3.2.19 on 2023-11-03 16:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('image', models.ImageField(null=True, upload_to='property_image/')),
                ('rent_per_year', models.DecimalField(decimal_places=0, max_digits=20)),
                ('lot_area', models.PositiveIntegerField()),
                ('bed_rooms', models.PositiveIntegerField()),
                ('bath_rooms', models.PositiveIntegerField()),
                ('luggage', models.BooleanField(default=True)),
                ('garage', models.PositiveIntegerField()),
                ('floor_area', models.PositiveIntegerField()),
                ('year_build', models.PositiveIntegerField()),
                ('water', models.BooleanField(default=True)),
                ('stories', models.PositiveIntegerField()),
                ('roofing', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], max_length=200)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 0, 47, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('review', models.TextField()),
                ('ratings', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 0, 47, tzinfo=utc))),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='agent_images/')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 11, 3, 15, 0, 47, tzinfo=utc))),
                ('properties', models.ManyToManyField(to='app.Property')),
            ],
        ),
    ]
