# Generated by Django 3.2.19 on 2023-11-04 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyreview',
            name='image',
            field=models.FileField(null=True, upload_to='property_review_image/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 55, 54, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='property',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 55, 54, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 18, 55, 54, tzinfo=utc)),
        ),
    ]
