# Generated by Django 3.2.19 on 2023-11-04 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231104_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 19, 25, 32, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='property',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 19, 25, 32, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.property'),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 19, 25, 32, tzinfo=utc)),
        ),
    ]
